Wh 82 transfered banner buttons component
alfa-code/web-handbook-next pull request #13
Opened 2022-08-07 20:14 UTC by AksenovKirill

1.  Исправил конфликты
2. Добавил компонент BannerButtons
3. Добавил компонент MainPageLink
4. Добавил компонент Icon
5. Добавил стили
6. Добавил memo

2022-08-09 12:09 UTC, Hydrock requested changes
Нужно немного подправить - а в целом все супер

2022-08-09 12:09 UTC, Hydrock commented on package-lock.json
> +{
Опять появился package-lock
Этот файл появляется при использовании npm
мы используем yarn

2022-08-09 12:09 UTC, Hydrock commented on src/components/banner-on-main-page/BannerOnMainPage.module.scss
> +@import "/src/styles/variables";
тебе не нужно импортировать переменные - я воказывал на видео - они автоматом будут в этой области видимости

2022-08-09 12:09 UTC, Hydrock commented on src/components/main-page-link/MainPageLink.module.scss
> +  // position: relative;
закомментированному коду не место в проекте

2022-08-09 12:09 UTC, Hydrock commented on src/components/main-page-link/MainPageLink.module.scss
> +    // position: static;
удали весь ненужны код

2022-08-10 19:12 UTC, AksenovKirill commented
1. Удалил package-lock
2. Удалил импорты
3.  Удалил закоментированный код
4. Удалил лишние стили

2022-08-11 13:05 UTC, merged