added UserInfo component
alfa-code/web-handbook-next pull request #5
Opened 2022-07-25 20:36 UTC by AksenovKirill

1. Добавил компонент для отображения информации о пользователе
2. Добавил компонент для отображения сообщения в случае, если информация не доступна
3. Добавил страницу в папку ssr/users для отображения информации о пользователе.

2022-07-26 08:00 UTC, Hubble999 reviewed
Папка .Idea кажется случайно попала в коммит, наверное в gitignore  надо добавить ее

2022-07-26 08:03 UTC, Hubble999 submitted a review, later dismissed

2022-07-26 11:52 UTC, Hydrock requested changes
Папку .idea нужно удалить
Это довольно серьезная оплошность - нужно проверять что попадает в index гита (зеленое) и что потом закоммитится

2022-07-26 12:06 UTC, Hydrock commented
@Hubble999 ты заапрувил, но в PR есть проблемы - обращай на это внимание

2022-07-26 18:50 UTC, AksenovKirill commented
@Hydrock @Hubble999 Добавил в gitignore папку и ее из проекта, сделал новый коммит и сделал push. Надеюсь это поможет. Спасибо!

2022-07-26 19:05 UTC, Hydrock commented
Нужно зарезолвить конфликты

2022-07-28 13:25 UTC, Hydrock approved these changes, later dismissed
Есть небольшой совет

2022-07-28 13:25 UTC, Hydrock commented on yarn.lock
> +  "integrity" "sha512-qZEWeccZCrHA2Au4/X05QW5CMdm4VjUDCrGq5gf1ZDcM4hRqreKrtwAn7yci9zfgAS9apvnsFXiGBHBAxZdK9A=="
тебе нужно быть внимательнее с тем что ты пушишь в ветку
ты установил зависимости и у тебя перегенерировался yarn.lock
но этого нет в рамках твоей задачи
ты либо не заметил, либо проинорировал

эта проблема дейстивтельно странная - обсуждается тут https://github.com/yarnpkg/yarn/issues/4379
но ее нужно решить иначе мы так и будем перегенеривовать этот файл

если нужно давайте созвонимся

@AksenovKirill @Hubble999 Обратите внимание

2022-07-28 13:25 UTC, Hydrock commented on yarn.lock
> +  integrity sha512-3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==
Тебе нужно настроить твой редактор чтобы по сохранению файла - в конец файла добавлялась пустая строка - это хорошая практика в программировании - так два файла не слипнутся при конкатенации

2022-07-28 13:52 UTC, Hubble999 commented on yarn.lock
> +  "integrity" "sha512-qZEWeccZCrHA2Au4/X05QW5CMdm4VjUDCrGq5gf1ZDcM4hRqreKrtwAn7yci9zfgAS9apvnsFXiGBHBAxZdK9A=="
Буду иметь ввиду, спасибо

2022-07-31 11:07 UTC, AksenovKirill commented on yarn.lock
> +  integrity sha512-3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==
настроил

2022-07-31 18:48 UTC, AksenovKirill commented on yarn.lock
> +  "integrity" "sha512-qZEWeccZCrHA2Au4/X05QW5CMdm4VjUDCrGq5gf1ZDcM4hRqreKrtwAn7yci9zfgAS9apvnsFXiGBHBAxZdK9A=="
Переустановил yarn

2022-08-02 18:05 UTC, Hubble999 approved these changes, later dismissed

2022-08-02 18:44 UTC, Hubble999 submitted a review, later dismissed

2022-08-02 18:44 UTC, AksenovKirill commented
Решил конфликты в yarn.lock

2022-08-06 18:54 UTC, AksenovKirill commented
1. Переустановил yarn.
2.  Проверил PR .

2022-08-09 12:13 UTC, Hydrock approved these changes

2022-08-10 19:14 UTC, merged