WH-71 added user information page ssg
alfa-code/web-handbook-next pull request #7
Opened 2022-07-26 19:35 UTC by AksenovKirill

1.  Добавил компонент для отображения информации о пользователе в pages/ssg.
2.  Использовал getStaticsProps() для отображения статических данных.
3.  Добавил компонент для отображения информации об ее отсуствуие.

2022-07-28 13:22 UTC, Hydrock requested changes
Апрувнул - но есть небольшие замечания

2022-07-28 13:22 UTC, Hydrock commented on pages/ssg/user.tsx
> +    const {message, avatar_url, login, email, location, created_at, userId} = props;
если в деструктуризации более чем 2 параметра - разноси их на разные строчки 
const {
  message,
  avatar_url,
  login, email,
  location,
  created_at, userId
} = props;

Почему? потому что если нужно будет внести изменения - гит покажет на какой строчке они были
в втоем варианте не понятно что конкретно изменилось

2022-07-28 13:22 UTC, Hydrock commented on pages/ssg/user.tsx
> +    const data = await fetch(`https://api.github.com/users/AksenovKirill`,
Это все нужно завернуть в try catch - ведь иначе функция ири неудачном запросе функция getStaticProps выбросит ошибку

2022-07-28 13:22 UTC, Hydrock commented on pages/ssg/user.tsx
> +    const {message, avatar_url, login, email, location, created_at, userId} = props;
и в других компонентах тоже

2022-07-28 13:23 UTC, Hydrock commented
Есть небольшие замечание - нужно поправить

2022-07-31 10:59 UTC, AksenovKirill commented on pages/ssg/user.tsx
> +    const {message, avatar_url, login, email, location, created_at, userId} = props;
Везде поправил, спасибо!

2022-07-31 11:06 UTC, AksenovKirill commented on pages/ssg/user.tsx
> +    const data = await fetch(`https://api.github.com/users/AksenovKirill`,
Не стал заворачивать, обсудили в Slack, что это не нужно

2022-08-01 07:36 UTC, Hydrock approved these changes

2022-08-02 18:07 UTC, Hubble999 approved these changes

2022-08-02 18:29 UTC, merged